// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs_rc0MCk5KxcTQyAaakjK9MhDxxsgeok',
    appId: '1:1821240632:web:12b872386b5a158ffae5cd',
    messagingSenderId: '1821240632',
    projectId: 'sistema-de-gestion-y-pqrs',
    authDomain: 'sistema-de-gestion-y-pqrs.firebaseapp.com',
    storageBucket: 'sistema-de-gestion-y-pqrs.firebasestorage.app',
    measurementId: 'G-93LHB07XYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFFV2fDpPPmGEUfFFUKfqUlf1aylI7Qik',
    appId: '1:1821240632:android:6a6758ae1d811693fae5cd',
    messagingSenderId: '1821240632',
    projectId: 'sistema-de-gestion-y-pqrs',
    storageBucket: 'sistema-de-gestion-y-pqrs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD90hBMIP0YmSCzdpZ-BJztwhyGlFnlBdc',
    appId: '1:1821240632:ios:e6e1726839af48d8fae5cd',
    messagingSenderId: '1821240632',
    projectId: 'sistema-de-gestion-y-pqrs',
    storageBucket: 'sistema-de-gestion-y-pqrs.firebasestorage.app',
    iosClientId:
        '1821240632-rn8f0f6lh8ifvg3h23dd90169b2otmol.apps.googleusercontent.com',
    iosBundleId: 'co.com.dts.dtsGestion',
  );
}
